syntax = "proto3";
package SDG.Naming;

option java_multiple_files = true;
option java_package = "generated.grpc.naming";
option java_outer_classname = "NamingProto";

//use  this message to pack service info
message ServiceInfo {
  string service_name = 1;
  string host = 2;
  int32 port = 3;
  string version = 4;
  repeated string capabilities = 5;
  map<string, string> metadata = 6;
}

message RegisterReply{
  bool ok = 1;
  string message = 2;
}

message DiscoverRequest{
  string service_name = 1;
}

message ServiceEndpoint{
  string host = 1;
  int32 port = 2;
  string version = 3;
  map<string, string> metadata = 4;
  int64 registered_epoch = 5;
}

message DiscoverReply{
  repeated ServiceEndpoint endpoints = 1;
}

service NamingService {
  rpc Register(ServiceInfo) returns (RegisterReply);
  rpc Discover(DiscoverRequest) returns (DiscoverReply);
}
